#!/bin/bash

# Stop and disable firewalld
sudo systemctl stop firewalld
sudo systemctl disable firewalld

# Install yum-utils
sudo yum install -y yum-utils

# Load necessary kernel modules
sudo modprobe bridge
sudo modprobe br_netfilter
sudo modprobe overlay

# Configure sysctl for Kubernetes CRI
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

# Apply sysctl settings
sysctl --system

# Add Docker CE repository and update packages
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf update -y

# Install containerd
dnf install -y containerd.io

# Create containerd configuration directory and generate default config
mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml

CONFIG_FILE="/etc/containerd/config.toml"

# Backup the original file
cp "$CONFIG_FILE" "$CONFIG_FILE.bak"

# Use sed to update the SystemdCgroup value to true
sed -i '/\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\]/,/\[/ s/SystemdCgroup = .*/SystemdCgroup = true/' "$CONFIG_FILE"

# Restart containerd to apply changes
systemctl restart containerd

echo "Updated SystemdCgroup to true and restarted containerd."


# Restart and enable containerd
systemctl restart containerd
systemctl enable containerd
systemctl status containerd

# Install required packages
yum install -y wget git vim-enhanced curl

# Add Kubernetes repository
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
EOF

# Update packages
dnf update -y

# Install Kubernetes components
sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

# Enable kubelet service
systemctl enable kubelet
